### ISSUE TITLE
Relative paths beginning with tilde doesn't work

### ISSUE THREAD

**Issue by rodrimc** [TeleMidia/LibPlay#1]
Creating a lp_Media using relative paths that start with a tilde (~) rises the following error:

lp-scene.c:408: Resource not found.: Resource not found.

**Comment by gflima** [comment]
The expansion of "~" is done by the shell.  This should work "play ~/path-to-file", the shell expands the prefixed tilde to $HOME, but "play '~/path-to-file'" won't work as the single quotes prevent shell expansion.
