### ISSUE TITLE
lib/lp-scene.c: Use fakesrc to generate a blank video stream in scene.

### ISSUE THREAD

**Issue by rodrimc** [TeleMidia/LibPlay#11]
Currently, we're using videotestsrc for this job, which is overkill. Moreover, it cannot generate a transparent stream.  We could use the fakesrc element, e.g.,
      gst-launch-1.0 fakesrc filltype=2 format=3                                                                        \
      ! capsfilter caps="video/x-raw,format=ARGB,framerate=0/1,width=800,height=600"       \
      ! videoconvert ! imagefreeze ! compositor name=comp sink_0::alpha=0                         \
      ! autovideosink videotestsrc ! comp.

**Comment by gflima** [comment]
Done
